baseURL = "https://dxmarathon.netlify.app/"
languageCode = 'en-us'
title = "DX Marathon"
theme = 'cq'

[markup.goldmark.renderer]
  unsafe = true
[markup.goldmark.parser.attribute]
  block = true
  attribute = true
