backend:
  name: github
  repo: dxmarathon/dxmarathon.org
  branch: main
#  name: git-gateway

publish_mode: editorial_workflow

media_folder: "content"
public_folder: "/"

collections:
  - name: news
    label: News
    folder: "content/news"
    create: true
    slug: "{{year}}/{{month}}-{{day}}-{{slug}}"
    nested:
      depth: 10
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: resources
    label: Resources
    folder: "content/resources"
    create: true
    slug: "{{slug}}"
    nested:
      depth: 10
    fields: # The fields for each document, usually in front matter
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Weight", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
